# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1165, 852)
        MainWindow.setStyleSheet("\n"
"QPalette{background:#444444;}*{outline:0px;color:#DCDCDC;}\n"
"\n"
"QWidget[form=\"true\"],QLabel[frameShape=\"1\"]{\n"
"border:1px solid #242424;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QWidget[form=\"bottom\"]{\n"
"\n"
"}\n"
"\n"
"QWidget[form=\"bottom\"] .QFrame{\n"
"border:1px solid #DCDCDC;\n"
"}\n"
"\n"
"QWidget[form=\"bottom\"] QLabel,QWidget[form=\"title\"] QLabel{\n"
"border-radius:0px;\n"
"color:#DCDCDC;\n"
"background:none;\n"
"border-style:none;\n"
"}\n"
"\n"
"QWidget[form=\"title\"],QWidget[nav=\"left\"],QWidget[nav=\"top\"] QAbstractButton{\n"
"border-style:none;\n"
"border-radius:0px;\n"
"padding:5px;\n"
"color:#DCDCDC;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
"\n"
"QWidget[nav=\"top\"] QAbstractButton:hover,QWidget[nav=\"top\"] QAbstractButton:pressed,QWidget[nav=\"top\"] QAbstractButton:checked{\n"
"border-style:solid;\n"
"border-width:0px 0px 2px 0px;\n"
"padding:4px 4px 2px 4px;\n"
"border-color:#00BB9E;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #646464,stop:1 #525252);\n"
"}\n"
"\n"
"QWidget[nav=\"left\"] QAbstractButton{\n"
"border-radius:0px;\n"
"color:#DCDCDC;\n"
"background:none;\n"
"border-style:none;\n"
"}\n"
"\n"
"QWidget[nav=\"left\"] QAbstractButton:hover{\n"
"color:#FFFFFF;\n"
"background-color:#00BB9E;\n"
"}\n"
"\n"
"QWidget[nav=\"left\"] QAbstractButton:checked,QWidget[nav=\"left\"] QAbstractButton:pressed{\n"
"color:#DCDCDC;\n"
"border-style:solid;\n"
"border-width:0px 0px 0px 2px;\n"
"padding:4px 4px 4px 2px;\n"
"border-color:#00BB9E;\n"
"background-color:#444444;\n"
"}\n"
"\n"
"QWidget[video=\"true\"] QLabel{\n"
"color:#DCDCDC;\n"
"border:1px solid #242424;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
"\n"
"QWidget[video=\"true\"] QLabel:focus{\n"
"border:1px solid #00BB9E;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #646464,stop:1 #525252);\n"
"}\n"
"\n"
"QLineEdit,QTextEdit,QPlainTextEdit,QSpinBox,QDoubleSpinBox,QComboBox,QDateEdit,QTimeEdit,QDateTimeEdit{\n"
"border:1px solid #242424;\n"
"border-radius:3px;\n"
"padding:2px;\n"
"background:none;\n"
"selection-background-color:#484848;\n"
"selection-color:#DCDCDC;\n"
"}\n"
"\n"
"QLineEdit:focus,QTextEdit:focus,QPlainTextEdit:focus,QSpinBox:focus,QDoubleSpinBox:focus,QComboBox:focus,QDateEdit:focus,QTimeEdit:focus,QDateTimeEdit:focus,QLineEdit:hover,QTextEdit:hover,QPlainTextEdit:hover,QSpinBox:hover,QDoubleSpinBox:hover,QComboBox:hover,QDateEdit:hover,QTimeEdit:hover,QDateTimeEdit:hover{\n"
"border:1px solid #242424;\n"
"}\n"
"\n"
"QLineEdit[echoMode=\"2\"]{\n"
"lineedit-password-character:9679;\n"
"}\n"
"\n"
".QFrame{\n"
"border:1px solid #242424;\n"
"border-radius:3px;\n"
"}\n"
"\n"
".QGroupBox{\n"
"border:1px solid #242424;\n"
"border-radius:5px;\n"
"margin-top:3ex;\n"
"}\n"
"\n"
".QGroupBox::title{\n"
"subcontrol-origin:margin;\n"
"position:relative;\n"
"left:10px;\n"
"}\n"
"\n"
".QPushButton,.QToolButton{\n"
"border-style:none;\n"
"border:1px solid #242424;\n"
"color:#DCDCDC;\n"
"padding:5px;\n"
"min-height:15px;\n"
"border-radius:5px;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
"\n"
".QPushButton:hover,.QToolButton:hover{\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #646464,stop:1 #525252);\n"
"}\n"
"\n"
".QPushButton:pressed,.QToolButton:pressed{\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
"\n"
".QToolButton::menu-indicator{\n"
"image:None;\n"
"}\n"
"\n"
"QToolButton#btnMenu,QPushButton#btnMenu_Min,QPushButton#btnMenu_Max,QPushButton#btnMenu_Close{\n"
"border-radius:3px;\n"
"color:#DCDCDC;\n"
"padding:3px;\n"
"margin:0px;\n"
"background:none;\n"
"border-style:none;\n"
"}\n"
"\n"
"QToolButton#btnMenu:hover,QPushButton#btnMenu_Min:hover,QPushButton#btnMenu_Max:hover{\n"
"color:#FFFFFF;\n"
"margin:1px 1px 2px 1px;\n"
"background-color:rgba(51,127,209,230);\n"
"}\n"
"\n"
"QPushButton#btnMenu_Close:hover{\n"
"color:#FFFFFF;\n"
"margin:1px 1px 2px 1px;\n"
"background-color:rgba(238,0,0,128);\n"
"}\n"
"\n"
"QRadioButton::indicator{\n"
"width:15px;\n"
"height:15px;\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked{\n"
"image:url(:/qss/psblack/radiobutton_unchecked.png);\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked:disabled{\n"
"image:url(:/qss/psblack/radiobutton_unchecked_disable.png);\n"
"}\n"
"\n"
"QRadioButton::indicator::checked{\n"
"image:url(:/qss/psblack/radiobutton_checked.png);\n"
"}\n"
"\n"
"QRadioButton::indicator::checked:disabled{\n"
"image:url(:/qss/psblack/radiobutton_checked_disable.png);\n"
"}\n"
"\n"
"QGroupBox::indicator,QTreeWidget::indicator,QListWidget::indicator{\n"
"padding:0px -3px 0px 3px;\n"
"}\n"
"\n"
"QCheckBox::indicator,QGroupBox::indicator,QTreeWidget::indicator,QListWidget::indicator{\n"
"width:13px;\n"
"height:13px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked,QGroupBox::indicator:unchecked,QTreeWidget::indicator:unchecked,QListWidget::indicator:unchecked{\n"
"image:url(:/qss/psblack/checkbox_unchecked.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:disabled,QGroupBox::indicator:unchecked:disabled,QTreeWidget::indicator:unchecked:disabled,QListWidget::indicator:disabled{\n"
"image:url(:/qss/psblack/checkbox_unchecked_disable.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked,QGroupBox::indicator:checked,QTreeWidget::indicator:checked,QListWidget::indicator:checked{\n"
"image:url(:/qss/psblack/checkbox_checked.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:disabled,QGroupBox::indicator:checked:disabled,QTreeWidget::indicator:checked:disabled,QListWidget::indicator:checked:disabled{\n"
"image:url(:/qss/psblack/checkbox_checked_disable.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:indeterminate,QGroupBox::indicator:indeterminate,QTreeWidget::indicator:indeterminate,QListWidget::indicator:indeterminate{\n"
"image:url(:/qss/psblack/checkbox_parcial.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:indeterminate:disabled,QGroupBox::indicator:indeterminate:disabled,QTreeWidget::indicator:indeterminate:disabled,QListWidget::indicator:indeterminate:disabled{\n"
"image:url(:/qss/psblack/checkbox_parcial_disable.png);\n"
"}\n"
"\n"
"QTimeEdit::up-button,QDateEdit::up-button,QDateTimeEdit::up-button,QDoubleSpinBox::up-button,QSpinBox::up-button{\n"
"image:url(:/qss/psblack/add_top.png);\n"
"width:10px;\n"
"height:10px;\n"
"padding:2px 5px 0px 0px;\n"
"}\n"
"\n"
"QTimeEdit::down-button,QDateEdit::down-button,QDateTimeEdit::down-button,QDoubleSpinBox::down-button,QSpinBox::down-button{\n"
"image:url(:/qss/psblack/add_bottom.png);\n"
"width:10px;\n"
"height:10px;\n"
"padding:0px 5px 2px 0px;\n"
"}\n"
"\n"
"QTimeEdit::up-button:pressed,QDateEdit::up-button:pressed,QDateTimeEdit::up-button:pressed,QDoubleSpinBox::up-button:pressed,QSpinBox::up-button:pressed{\n"
"top:-2px;\n"
"}\n"
"  \n"
"QTimeEdit::down-button:pressed,QDateEdit::down-button:pressed,QDateTimeEdit::down-button:pressed,QDoubleSpinBox::down-button:pressed,QSpinBox::down-button:pressed,QSpinBox::down-button:pressed{\n"
"bottom:-2px;\n"
"}\n"
"\n"
"QComboBox::down-arrow,QDateEdit[calendarPopup=\"true\"]::down-arrow,QTimeEdit[calendarPopup=\"true\"]::down-arrow,QDateTimeEdit[calendarPopup=\"true\"]::down-arrow{\n"
"image:url(:/qss/psblack/add_bottom.png);\n"
"width:10px;\n"
"height:10px;\n"
"right:2px;\n"
"}\n"
"\n"
"QComboBox::drop-down,QDateEdit::drop-down,QTimeEdit::drop-down,QDateTimeEdit::drop-down{\n"
"subcontrol-origin:padding;\n"
"subcontrol-position:top right;\n"
"width:15px;\n"
"border-left-width:0px;\n"
"border-left-style:solid;\n"
"border-top-right-radius:3px;\n"
"border-bottom-right-radius:3px;\n"
"border-left-color:#242424;\n"
"}\n"
"\n"
"QComboBox::drop-down:on{\n"
"top:1px;\n"
"}\n"
"\n"
"QMenuBar::item{\n"
"color:#DCDCDC;\n"
"background-color:#484848;\n"
"margin:0px;\n"
"padding:3px 10px;\n"
"}\n"
"\n"
"QMenu,QMenuBar,QMenu:disabled,QMenuBar:disabled{\n"
"color:#DCDCDC;\n"
"background-color:#484848;\n"
"border:1px solid #242424;\n"
"margin:0px;\n"
"}\n"
"\n"
"QMenu::item{\n"
"padding:3px 20px;\n"
"}\n"
"\n"
"QMenu::indicator{\n"
"width:13px;\n"
"height:13px;\n"
"}\n"
"\n"
"QMenu::item:selected,QMenuBar::item:selected{\n"
"color:#DCDCDC;\n"
"border:0px solid #242424;\n"
"background:#646464;\n"
"}\n"
"\n"
"QMenu::separator{\n"
"height:1px;\n"
"background:#242424;\n"
"}\n"
"\n"
"QProgressBar{\n"
"min-height:10px;\n"
"background:#484848;\n"
"border-radius:5px;\n"
"text-align:center;\n"
"border:1px solid #484848;\n"
"}\n"
"\n"
"QProgressBar:chunk{\n"
"border-radius:5px;\n"
"background-color:#242424;\n"
"}\n"
"\n"
"QSlider::groove:horizontal{\n"
"background:#484848;\n"
"height:8px;\n"
"border-radius:4px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal{\n"
"background:#484848;\n"
"height:8px;\n"
"border-radius:4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal{\n"
"background:#242424;\n"
"height:8px;\n"
"border-radius:4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal{\n"
"width:13px;\n"
"margin-top:-3px;\n"
"margin-bottom:-3px;\n"
"border-radius:6px;\n"
"background:qradialgradient(spread:pad,cx:0.5,cy:0.5,radius:0.5,fx:0.5,fy:0.5,stop:0.6 #444444,stop:0.8 #242424);\n"
"}\n"
"\n"
"QSlider::groove:vertical{\n"
"width:8px;\n"
"border-radius:4px;\n"
"background:#484848;\n"
"}\n"
"\n"
"QSlider::add-page:vertical{\n"
"width:8px;\n"
"border-radius:4px;\n"
"background:#484848;\n"
"}\n"
"\n"
"QSlider::sub-page:vertical{\n"
"width:8px;\n"
"border-radius:4px;\n"
"background:#242424;\n"
"}\n"
"\n"
"QSlider::handle:vertical{\n"
"height:14px;\n"
"margin-left:-3px;\n"
"margin-right:-3px;\n"
"border-radius:6px;\n"
"background:qradialgradient(spread:pad,cx:0.5,cy:0.5,radius:0.5,fx:0.5,fy:0.5,stop:0.6 #444444,stop:0.8 #242424);\n"
"}\n"
"\n"
"QScrollBar:horizontal{\n"
"background:#484848;\n"
"padding:0px;\n"
"border-radius:6px;\n"
"max-height:12px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal{\n"
"background:#525252;\n"
"min-width:50px;\n"
"border-radius:6px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover{\n"
"background:#242424;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:pressed{\n"
"background:#242424;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal{\n"
"background:none;\n"
"}\n"
"\n"
"QScrollBar::sub-page:horizontal{\n"
"background:none;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal{\n"
"background:none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal{\n"
"background:none;\n"
"}\n"
"\n"
"QScrollBar:vertical{\n"
"background:#484848;\n"
"padding:0px;\n"
"border-radius:6px;\n"
"max-width:12px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical{\n"
"background:#525252;\n"
"min-height:50px;\n"
"border-radius:6px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover{\n"
"background:#242424;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:pressed{\n"
"background:#242424;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical{\n"
"background:none;\n"
"}\n"
"\n"
"QScrollBar::sub-page:vertical{\n"
"background:none;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical{\n"
"background:none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical{\n"
"background:none;\n"
"}\n"
"\n"
"QScrollArea{\n"
"border:0px;\n"
"}\n"
"\n"
"QTreeView,QListView,QTableView,QTabWidget::pane{\n"
"border:1px solid #242424;\n"
"selection-background-color:#646464;\n"
"selection-color:#DCDCDC;\n"
"alternate-background-color:#525252;\n"
"gridline-color:#242424;\n"
"}\n"
"\n"
"QTreeView::branch:closed:has-children{\n"
"margin:4px;\n"
"border-image:url(:/qss/psblack/branch_open.png);\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children{\n"
"margin:4px;\n"
"border-image:url(:/qss/psblack/branch_close.png);\n"
"}\n"
"\n"
"QTreeView,QListView,QTableView,QSplitter::handle,QTreeView::branch{\n"
"background:#444444;\n"
"}\n"
"\n"
"QTableView::item:selected,QListView::item:selected,QTreeView::item:selected{\n"
"color:#DCDCDC;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
"\n"
"QTableView::item:hover,QListView::item:hover,QTreeView::item:hover{\n"
"color:#DCDCDC;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #646464,stop:1 #525252);\n"
"}\n"
"\n"
"QTableView::item,QListView::item,QTreeView::item{\n"
"padding:1px;\n"
"margin:0px;\n"
"}\n"
"\n"
"QHeaderView::section,QTableCornerButton:section{\n"
"padding:3px;\n"
"margin:0px;\n"
"color:#DCDCDC;\n"
"border:1px solid #242424;\n"
"border-left-width:0px;\n"
"border-right-width:1px;\n"
"border-top-width:0px;\n"
"border-bottom-width:1px;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #646464,stop:1 #525252);\n"
"}\n"
"\n"
"QTabBar::tab{\n"
"border:1px solid #242424;\n"
"color:#DCDCDC;\n"
"margin:0px;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #646464,stop:1 #525252);\n"
"}\n"
"\n"
"QTabBar::tab:selected,QTabBar::tab:hover{\n"
"border-style:solid;\n"
"border-color:#00BB9E;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
"\n"
"QTabBar::tab:top,QTabBar::tab:bottom{\n"
"padding:3px 8px 3px 8px;\n"
"}\n"
"\n"
"QTabBar::tab:left,QTabBar::tab:right{\n"
"padding:8px 3px 8px 3px;\n"
"}\n"
"\n"
"QTabBar::tab:top:selected,QTabBar::tab:top:hover{\n"
"border-width:2px 0px 0px 0px;\n"
"}\n"
"\n"
"QTabBar::tab:right:selected,QTabBar::tab:right:hover{\n"
"border-width:0px 0px 0px 2px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:selected,QTabBar::tab:bottom:hover{\n"
"border-width:0px 0px 2px 0px;\n"
"}\n"
"\n"
"QTabBar::tab:left:selected,QTabBar::tab:left:hover{\n"
"border-width:0px 2px 0px 0px;\n"
"}\n"
"\n"
"QTabBar::tab:first:top:selected,QTabBar::tab:first:top:hover,QTabBar::tab:first:bottom:selected,QTabBar::tab:first:bottom:hover{\n"
"border-left-width:1px;\n"
"border-left-color:#242424;\n"
"}\n"
"\n"
"QTabBar::tab:first:left:selected,QTabBar::tab:first:left:hover,QTabBar::tab:first:right:selected,QTabBar::tab:first:right:hover{\n"
"border-top-width:1px;\n"
"border-top-color:#242424;\n"
"}\n"
"\n"
"QTabBar::tab:last:top:selected,QTabBar::tab:last:top:hover,QTabBar::tab:last:bottom:selected,QTabBar::tab:last:bottom:hover{\n"
"border-right-width:1px;\n"
"border-right-color:#242424;\n"
"}\n"
"\n"
"QTabBar::tab:last:left:selected,QTabBar::tab:last:left:hover,QTabBar::tab:last:right:selected,QTabBar::tab:last:right:hover{\n"
"border-bottom-width:1px;\n"
"border-bottom-color:#242424;\n"
"}\n"
"\n"
"QStatusBar::item{\n"
"border:0px solid #484848;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QToolBox::tab,QGroupBox#gboxDevicePanel,QGroupBox#gboxDeviceTitle,QFrame#gboxDevicePanel,QFrame#gboxDeviceTitle{\n"
"padding:3px;\n"
"border-radius:5px;\n"
"color:#DCDCDC;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
"\n"
"QToolTip{\n"
"border:0px solid #DCDCDC;\n"
"padding:1px;\n"
"color:#DCDCDC;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
"\n"
"QToolBox::tab:selected{\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #646464,stop:1 #525252);\n"
"}\n"
"\n"
"QPrintPreviewDialog QToolButton{\n"
"border:0px solid #DCDCDC;\n"
"border-radius:0px;\n"
"margin:0px;\n"
"padding:3px;\n"
"background:none;\n"
"}\n"
"\n"
"QColorDialog QPushButton,QFileDialog QPushButton{\n"
"min-width:80px;\n"
"}\n"
"\n"
"QToolButton#qt_calendar_prevmonth{\n"
"icon-size:0px;\n"
"min-width:20px;\n"
"image:url(:/qss/psblack/calendar_prevmonth.png);\n"
"}\n"
"\n"
"QToolButton#qt_calendar_nextmonth{\n"
"icon-size:0px;\n"
"min-width:20px;\n"
"image:url(:/qss/psblack/calendar_nextmonth.png);\n"
"}\n"
"\n"
"QToolButton#qt_calendar_prevmonth,QToolButton#qt_calendar_nextmonth,QToolButton#qt_calendar_monthbutton,QToolButton#qt_calendar_yearbutton{\n"
"border:0px solid #DCDCDC;\n"
"border-radius:3px;\n"
"margin:3px 3px 3px 3px;\n"
"padding:3px;\n"
"background:none;\n"
"}\n"
"\n"
"QToolButton#qt_calendar_prevmonth:hover,QToolButton#qt_calendar_nextmonth:hover,QToolButton#qt_calendar_monthbutton:hover,QToolButton#qt_calendar_yearbutton:hover,QToolButton#qt_calendar_prevmonth:pressed,QToolButton#qt_calendar_nextmonth:pressed,QToolButton#qt_calendar_monthbutton:pressed,QToolButton#qt_calendar_yearbutton:pressed{\n"
"border:1px solid #242424;\n"
"}\n"
"\n"
"QCalendarWidget QSpinBox#qt_calendar_yearedit{\n"
"margin:2px;\n"
"}\n"
"\n"
"QCalendarWidget QToolButton::menu-indicator{\n"
"image:None;\n"
"}\n"
"\n"
"QCalendarWidget QTableView{\n"
"border-width:0px;\n"
"}\n"
"\n"
"QCalendarWidget QWidget#qt_calendar_navigationbar{\n"
"border:1px solid #242424;\n"
"border-width:1px 1px 0px 1px;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item{\n"
"min-height:20px;\n"
"min-width:10px;\n"
"}\n"
"\n"
"QTableView[model=\"true\"]::item{\n"
"padding:0px;\n"
"margin:0px;\n"
"}\n"
"\n"
"QTableView QLineEdit,QTableView QComboBox,QTableView QSpinBox,QTableView QDoubleSpinBox,QTableView QDateEdit,QTableView QTimeEdit,QTableView QDateTimeEdit{\n"
"border-width:0px;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QTableView QLineEdit:focus,QTableView QComboBox:focus,QTableView QSpinBox:focus,QTableView QDoubleSpinBox:focus,QTableView QDateEdit:focus,QTableView QTimeEdit:focus,QTableView QDateTimeEdit:focus{\n"
"border-width:0px;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QLineEdit,QTextEdit,QPlainTextEdit,QSpinBox,QDoubleSpinBox,QComboBox,QDateEdit,QTimeEdit,QDateTimeEdit{\n"
"background:#444444;\n"
"}\n"
"\n"
"*:disabled{\n"
"background:#444444;\n"
"border-color:#484848;\n"
"}\n"
"QMessageBox{\n"
"font:16px,black;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background:#302a2a")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.timeLabel = QtWidgets.QLabel(self.centralwidget)
        self.timeLabel.setMinimumSize(QtCore.QSize(0, 35))
        self.timeLabel.setStyleSheet("background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"font: 20pt \"Terminator Two\";\n"
"border:3px solid qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #646464,stop:1 #525252);")
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.gridLayout.addWidget(self.timeLabel, 2, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("border:none;\n"
"\n"
"font: 16pt \"华光黑变_CNKI\";")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.tab1)
        self.frame.setStyleSheet("background:#444444")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.originImgLabel = QtWidgets.QLabel(self.frame)
        self.originImgLabel.setStyleSheet("")
        self.originImgLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.originImgLabel.setObjectName("originImgLabel")
        self.horizontalLayout.addWidget(self.originImgLabel)
        self.resultImgLabel = QtWidgets.QLabel(self.frame)
        self.resultImgLabel.setStyleSheet("")
        self.resultImgLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.resultImgLabel.setObjectName("resultImgLabel")
        self.horizontalLayout.addWidget(self.resultImgLabel)
        self.gridLayout_2.addWidget(self.frame, 2, 0, 1, 4)
        self.resultTable = QtWidgets.QTableWidget(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultTable.sizePolicy().hasHeightForWidth())
        self.resultTable.setSizePolicy(sizePolicy)
        self.resultTable.setMinimumSize(QtCore.QSize(0, 0))
        self.resultTable.setMaximumSize(QtCore.QSize(16777215, 60))
        self.resultTable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.resultTable.setAutoFillBackground(False)
        self.resultTable.setStyleSheet("background:#444444;\n"
"font: 10pt \"方正粗黑宋简体\";")
        self.resultTable.setMidLineWidth(1)
        self.resultTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.resultTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.resultTable.setAutoScroll(True)
        self.resultTable.setShowGrid(True)
        self.resultTable.setGridStyle(QtCore.Qt.DashLine)
        self.resultTable.setObjectName("resultTable")
        self.resultTable.setColumnCount(3)
        self.resultTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        item.setFont(font)
        self.resultTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(10)
        item.setFont(font)
        self.resultTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.resultTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.resultTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.resultTable.setItem(0, 2, item)
        self.resultTable.horizontalHeader().setVisible(True)
        self.resultTable.horizontalHeader().setCascadingSectionResizes(False)
        self.resultTable.horizontalHeader().setDefaultSectionSize(350)
        self.resultTable.horizontalHeader().setHighlightSections(False)
        self.resultTable.horizontalHeader().setMinimumSectionSize(23)
        self.resultTable.horizontalHeader().setSortIndicatorShown(False)
        self.resultTable.verticalHeader().setVisible(True)
        self.resultTable.verticalHeader().setCascadingSectionResizes(False)
        self.resultTable.verticalHeader().setHighlightSections(False)
        self.resultTable.verticalHeader().setSortIndicatorShown(False)
        self.resultTable.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.resultTable, 3, 0, 1, 4)
        self.detectbtn = QtWidgets.QPushButton(self.tab1)
        self.detectbtn.setStyleSheet("\n"
".QPushButton,.QToolButton{\n"
"border-style:none;\n"
"border:1px solid #242424;\n"
"color:#DCDCDC;\n"
"font: 22pt \"华光粗黑_CNKI\";\n"
"padding:5px;\n"
"min-height:15px;\n"
"border-radius:5px;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
"\n"
".QPushButton:hover,.QToolButton:hover{\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #646464,stop:1 #525252);\n"
"}\n"
"\n"
".QPushButton:pressed,.QToolButton:pressed{\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("static/瀑布流横向_waterfalls-h.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.detectbtn.setIcon(icon)
        self.detectbtn.setIconSize(QtCore.QSize(35, 35))
        self.detectbtn.setObjectName("detectbtn")
        self.gridLayout_2.addWidget(self.detectbtn, 0, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.tab1)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setMinimumSize(QtCore.QSize(80, 0))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 39))
        self.label_5.setStyleSheet("background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #444444,stop:1 #383838);\n"
"font: 20pt \"华光超粗黑_CNKI\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.IdInput = QtWidgets.QLineEdit(self.frame_2)
        self.IdInput.setStyleSheet("background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"font: 20pt \"华光超粗黑_CNKI\";")
        self.IdInput.setObjectName("IdInput")
        self.horizontalLayout_2.addWidget(self.IdInput)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setMinimumSize(QtCore.QSize(80, 0))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 39))
        self.label_2.setStyleSheet("background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #444444,stop:1 #383838);\n"
"font: 20pt \"华光超粗黑_CNKI\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.nameInput = QtWidgets.QLineEdit(self.frame_2)
        self.nameInput.setStyleSheet("background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"font: 20pt \"华光超粗黑_CNKI\";")
        self.nameInput.setObjectName("nameInput")
        self.horizontalLayout_2.addWidget(self.nameInput)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setMinimumSize(QtCore.QSize(80, 0))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 39))
        self.label_3.setStyleSheet("background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #444444,stop:1 #383838);\n"
"font: 20pt \"华光超粗黑_CNKI\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.genderInput = QtWidgets.QLineEdit(self.frame_2)
        self.genderInput.setStyleSheet("background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"font: 20pt \"华光超粗黑_CNKI\";")
        self.genderInput.setObjectName("genderInput")
        self.horizontalLayout_2.addWidget(self.genderInput)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setMinimumSize(QtCore.QSize(80, 0))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 39))
        self.label_4.setStyleSheet("background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #444444,stop:1 #383838);\n"
"font: 20pt \"华光超粗黑_CNKI\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.ageInput = QtWidgets.QLineEdit(self.frame_2)
        self.ageInput.setStyleSheet("background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"font: 20pt \"华光超粗黑_CNKI\";")
        self.ageInput.setObjectName("ageInput")
        self.horizontalLayout_2.addWidget(self.ageInput)
        self.gridLayout_2.addWidget(self.frame_2, 1, 0, 1, 4)
        self.savebtn = QtWidgets.QPushButton(self.tab1)
        self.savebtn.setStyleSheet("\n"
".QPushButton,.QToolButton{\n"
"border-style:none;\n"
"border:1px solid #242424;\n"
"color:#DCDCDC;\n"
"font: 22pt \"华光粗黑_CNKI\";\n"
"padding:5px;\n"
"min-height:15px;\n"
"border-radius:5px;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
"\n"
".QPushButton:hover,.QToolButton:hover{\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #646464,stop:1 #525252);\n"
"}\n"
"\n"
".QPushButton:pressed,.QToolButton:pressed{\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
"\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("static/保存硬盘_save-one.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.savebtn.setIcon(icon1)
        self.savebtn.setIconSize(QtCore.QSize(35, 35))
        self.savebtn.setObjectName("savebtn")
        self.gridLayout_2.addWidget(self.savebtn, 0, 2, 1, 1)
        self.uploadbtn = QtWidgets.QPushButton(self.tab1)
        self.uploadbtn.setMinimumSize(QtCore.QSize(0, 27))
        self.uploadbtn.setStyleSheet("\n"
".QPushButton,.QToolButton{\n"
"border-style:none;\n"
"border:1px solid #242424;\n"
"color:#DCDCDC;\n"
"font: 22pt \"华光粗黑_CNKI\";\n"
"padding:5px;\n"
"min-height:15px;\n"
"border-radius:5px;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
"\n"
".QPushButton:hover,.QToolButton:hover{\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #646464,stop:1 #525252);\n"
"}\n"
"\n"
".QPushButton:pressed,.QToolButton:pressed{\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
"\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("static/图片上传_upload-picture.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uploadbtn.setIcon(icon2)
        self.uploadbtn.setIconSize(QtCore.QSize(35, 35))
        self.uploadbtn.setObjectName("uploadbtn")
        self.gridLayout_2.addWidget(self.uploadbtn, 0, 0, 1, 1)
        self.enterbtn = QtWidgets.QPushButton(self.tab1)
        self.enterbtn.setStyleSheet("\n"
".QPushButton,.QToolButton{\n"
"border-style:none;\n"
"border:1px solid #242424;\n"
"color:#DCDCDC;\n"
"font: 22pt \"华光粗黑_CNKI\";\n"
"padding:5px;\n"
"min-height:15px;\n"
"border-radius:5px;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
"\n"
".QPushButton:hover,.QToolButton:hover{\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #646464,stop:1 #525252);\n"
"}\n"
"\n"
".QPushButton:pressed,.QToolButton:pressed{\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
"\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("static/头像_avatar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.enterbtn.setIcon(icon3)
        self.enterbtn.setIconSize(QtCore.QSize(35, 35))
        self.enterbtn.setObjectName("enterbtn")
        self.gridLayout_2.addWidget(self.enterbtn, 0, 3, 1, 1)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("static/点滴_infusion.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab1, icon4, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.uploadbtn2 = QtWidgets.QPushButton(self.tab2)
        self.uploadbtn2.setMinimumSize(QtCore.QSize(0, 27))
        self.uploadbtn2.setStyleSheet("\n"
".QPushButton,.QToolButton{\n"
"border-style:none;\n"
"border:1px solid #242424;\n"
"color:#DCDCDC;\n"
"font: 22pt \"华光粗黑_CNKI\";\n"
"padding:5px;\n"
"min-height:15px;\n"
"border-radius:5px;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
"\n"
".QPushButton:hover,.QToolButton:hover{\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #646464,stop:1 #525252);\n"
"}\n"
"\n"
".QPushButton:pressed,.QToolButton:pressed{\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
"\n"
"")
        self.uploadbtn2.setIcon(icon2)
        self.uploadbtn2.setIconSize(QtCore.QSize(35, 35))
        self.uploadbtn2.setObjectName("uploadbtn2")
        self.gridLayout_5.addWidget(self.uploadbtn2, 0, 0, 1, 1)
        self.frame1 = QtWidgets.QFrame(self.tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame1.sizePolicy().hasHeightForWidth())
        self.frame1.setSizePolicy(sizePolicy)
        self.frame1.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame1.setObjectName("frame1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame1)
        self.gridLayout_3.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.frame1)
        self.groupBox.setStyleSheet("QGroupBox::title { subcontrol-origin: margin; subcontrol-position: left; }\n"
"font: 14pt \"华光超粗黑_CNKI\";")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(115, 10, 1001, 61))
        self.label_14.setStyleSheet("background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"font: 13pt \"华光超粗黑_CNKI\";")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame1, 3, 0, 1, 4)
        self.savebtn2 = QtWidgets.QPushButton(self.tab2)
        self.savebtn2.setStyleSheet("\n"
".QPushButton,.QToolButton{\n"
"border-style:none;\n"
"border:1px solid #242424;\n"
"color:#DCDCDC;\n"
"font: 22pt \"华光粗黑_CNKI\";\n"
"padding:5px;\n"
"min-height:15px;\n"
"border-radius:5px;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
"\n"
".QPushButton:hover,.QToolButton:hover{\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #646464,stop:1 #525252);\n"
"}\n"
"\n"
".QPushButton:pressed,.QToolButton:pressed{\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
"\n"
"")
        self.savebtn2.setIcon(icon1)
        self.savebtn2.setIconSize(QtCore.QSize(35, 35))
        self.savebtn2.setObjectName("savebtn2")
        self.gridLayout_5.addWidget(self.savebtn2, 0, 2, 1, 1)
        self.frame2 = QtWidgets.QFrame(self.tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame2.sizePolicy().hasHeightForWidth())
        self.frame2.setSizePolicy(sizePolicy)
        self.frame2.setStyleSheet("background:#444444")
        self.frame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame2.setObjectName("frame2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.originImgLabel_2 = QtWidgets.QLabel(self.frame2)
        self.originImgLabel_2.setStyleSheet("")
        self.originImgLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.originImgLabel_2.setObjectName("originImgLabel_2")
        self.horizontalLayout_5.addWidget(self.originImgLabel_2)
        self.resultImgLabel_2 = QtWidgets.QLabel(self.frame2)
        self.resultImgLabel_2.setStyleSheet("")
        self.resultImgLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.resultImgLabel_2.setObjectName("resultImgLabel_2")
        self.horizontalLayout_5.addWidget(self.resultImgLabel_2)
        self.gridLayout_5.addWidget(self.frame2, 2, 0, 1, 4)
        self.detectbtn2 = QtWidgets.QPushButton(self.tab2)
        self.detectbtn2.setStyleSheet("\n"
".QPushButton,.QToolButton{\n"
"border-style:none;\n"
"border:1px solid #242424;\n"
"color:#DCDCDC;\n"
"font: 22pt \"华光粗黑_CNKI\";\n"
"padding:5px;\n"
"min-height:15px;\n"
"border-radius:5px;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
"\n"
".QPushButton:hover,.QToolButton:hover{\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #646464,stop:1 #525252);\n"
"}\n"
"\n"
".QPushButton:pressed,.QToolButton:pressed{\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}")
        self.detectbtn2.setIcon(icon)
        self.detectbtn2.setIconSize(QtCore.QSize(35, 35))
        self.detectbtn2.setObjectName("detectbtn2")
        self.gridLayout_5.addWidget(self.detectbtn2, 0, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.tab2)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setMinimumSize(QtCore.QSize(80, 0))
        self.label_11.setStyleSheet("background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #444444,stop:1 #383838);\n"
"font: 20pt \"华光超粗黑_CNKI\";")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.IdInput_3 = QtWidgets.QLineEdit(self.frame_3)
        self.IdInput_3.setStyleSheet("background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"font: 20pt \"华光超粗黑_CNKI\";")
        self.IdInput_3.setObjectName("IdInput_3")
        self.horizontalLayout_4.addWidget(self.IdInput_3)
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setMinimumSize(QtCore.QSize(80, 0))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 42))
        self.label_10.setStyleSheet("background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #444444,stop:1 #383838);\n"
"font: 20pt \"华光超粗黑_CNKI\";")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.nameInput_3 = QtWidgets.QLineEdit(self.frame_3)
        self.nameInput_3.setStyleSheet("background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"font: 20pt \"华光超粗黑_CNKI\";")
        self.nameInput_3.setObjectName("nameInput_3")
        self.horizontalLayout_4.addWidget(self.nameInput_3)
        self.label_13 = QtWidgets.QLabel(self.frame_3)
        self.label_13.setMinimumSize(QtCore.QSize(80, 0))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 42))
        self.label_13.setStyleSheet("background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #444444,stop:1 #383838);\n"
"font: 20pt \"华光超粗黑_CNKI\";")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_4.addWidget(self.label_13)
        self.genderInput_3 = QtWidgets.QLineEdit(self.frame_3)
        self.genderInput_3.setStyleSheet("background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"font: 20pt \"华光超粗黑_CNKI\";")
        self.genderInput_3.setObjectName("genderInput_3")
        self.horizontalLayout_4.addWidget(self.genderInput_3)
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setMinimumSize(QtCore.QSize(80, 0))
        self.label_12.setStyleSheet("background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #444444,stop:1 #383838);\n"
"font: 20pt \"华光超粗黑_CNKI\";")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12)
        self.ageInput_3 = QtWidgets.QLineEdit(self.frame_3)
        self.ageInput_3.setStyleSheet("background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"font: 20pt \"华光超粗黑_CNKI\";")
        self.ageInput_3.setObjectName("ageInput_3")
        self.horizontalLayout_4.addWidget(self.ageInput_3)
        self.gridLayout_5.addWidget(self.frame_3, 1, 0, 1, 4)
        self.enterbtn2 = QtWidgets.QPushButton(self.tab2)
        self.enterbtn2.setStyleSheet("\n"
".QPushButton,.QToolButton{\n"
"border-style:none;\n"
"border:1px solid #242424;\n"
"color:#DCDCDC;\n"
"font: 22pt \"华光粗黑_CNKI\";\n"
"padding:5px;\n"
"min-height:15px;\n"
"border-radius:5px;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
"\n"
".QPushButton:hover,.QToolButton:hover{\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #646464,stop:1 #525252);\n"
"}\n"
"\n"
".QPushButton:pressed,.QToolButton:pressed{\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
"\n"
"")
        self.enterbtn2.setIcon(icon3)
        self.enterbtn2.setIconSize(QtCore.QSize(35, 35))
        self.enterbtn2.setObjectName("enterbtn2")
        self.gridLayout_5.addWidget(self.enterbtn2, 0, 3, 1, 1)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("static/病菌_germs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab2, icon5, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.batchbtn = QtWidgets.QPushButton(self.tab3)
        self.batchbtn.setMinimumSize(QtCore.QSize(0, 27))
        self.batchbtn.setStyleSheet("\n"
".QPushButton,.QToolButton{\n"
"border-style:none;\n"
"border:1px solid #242424;\n"
"color:#DCDCDC;\n"
"font: 22pt \"华光粗黑_CNKI\";\n"
"padding:5px;\n"
"min-height:15px;\n"
"border-radius:5px;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
"\n"
".QPushButton:hover,.QToolButton:hover{\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #646464,stop:1 #525252);\n"
"}\n"
"\n"
".QPushButton:pressed,.QToolButton:pressed{\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
"\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("static/文件夹-上传_folder-upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.batchbtn.setIcon(icon6)
        self.batchbtn.setIconSize(QtCore.QSize(35, 35))
        self.batchbtn.setObjectName("batchbtn")
        self.gridLayout_4.addWidget(self.batchbtn, 0, 0, 1, 1)
        self.generatebtn = QtWidgets.QPushButton(self.tab3)
        self.generatebtn.setMinimumSize(QtCore.QSize(0, 27))
        self.generatebtn.setStyleSheet("\n"
".QPushButton,.QToolButton{\n"
"border-style:none;\n"
"border:1px solid #242424;\n"
"color:#DCDCDC;\n"
"font: 22pt \"华光粗黑_CNKI\";\n"
"padding:5px;\n"
"min-height:15px;\n"
"border-radius:5px;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
"\n"
".QPushButton:hover,.QToolButton:hover{\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #646464,stop:1 #525252);\n"
"}\n"
"\n"
".QPushButton:pressed,.QToolButton:pressed{\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
"\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("static/数据图_chart-pie-one.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.generatebtn.setIcon(icon7)
        self.generatebtn.setIconSize(QtCore.QSize(35, 35))
        self.generatebtn.setObjectName("generatebtn")
        self.gridLayout_4.addWidget(self.generatebtn, 0, 2, 1, 1)
        self.progressbtn = QtWidgets.QPushButton(self.tab3)
        self.progressbtn.setMinimumSize(QtCore.QSize(0, 27))
        self.progressbtn.setStyleSheet("\n"
".QPushButton,.QToolButton{\n"
"border-style:none;\n"
"border:1px solid #242424;\n"
"color:#DCDCDC;\n"
"font: 22pt \"华光粗黑_CNKI\";\n"
"padding:5px;\n"
"min-height:15px;\n"
"border-radius:5px;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
"\n"
".QPushButton:hover,.QToolButton:hover{\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #646464,stop:1 #525252);\n"
"}\n"
"\n"
".QPushButton:pressed,.QToolButton:pressed{\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
"\n"
"")
        self.progressbtn.setIcon(icon)
        self.progressbtn.setIconSize(QtCore.QSize(35, 35))
        self.progressbtn.setObjectName("progressbtn")
        self.gridLayout_4.addWidget(self.progressbtn, 0, 1, 1, 1)
        self.savebtn3 = QtWidgets.QPushButton(self.tab3)
        self.savebtn3.setMinimumSize(QtCore.QSize(0, 27))
        self.savebtn3.setStyleSheet("\n"
".QPushButton,.QToolButton{\n"
"border-style:none;\n"
"border:1px solid #242424;\n"
"color:#DCDCDC;\n"
"font: 22pt \"华光粗黑_CNKI\";\n"
"padding:5px;\n"
"min-height:15px;\n"
"border-radius:5px;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
"\n"
".QPushButton:hover,.QToolButton:hover{\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #646464,stop:1 #525252);\n"
"}\n"
"\n"
".QPushButton:pressed,.QToolButton:pressed{\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
"\n"
"")
        self.savebtn3.setIcon(icon1)
        self.savebtn3.setIconSize(QtCore.QSize(35, 35))
        self.savebtn3.setObjectName("savebtn3")
        self.gridLayout_4.addWidget(self.savebtn3, 0, 3, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.tab3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setStyleSheet("background:#444444;\n"
"font: 24pt \"楷体\";")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.gridLayout_4.addWidget(self.frame_4, 1, 0, 1, 4)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("static/细胞_cell.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab3, icon8, "")
        self.tab4 = QtWidgets.QWidget()
        self.tab4.setObjectName("tab4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab4)
        self.comboBox_2.setMinimumSize(QtCore.QSize(250, 0))
        self.comboBox_2.setStyleSheet("background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"font: 20pt \"华光超粗黑_CNKI\";")
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_7.addWidget(self.comboBox_2, 0, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab4)
        self.label_15.setMinimumSize(QtCore.QSize(80, 0))
        self.label_15.setStyleSheet("background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #444444,stop:1 #383838);\n"
"font: 20pt \"华光超粗黑_CNKI\";")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 0, 0, 1, 1)
        self.IdInput_2 = QtWidgets.QLineEdit(self.tab4)
        self.IdInput_2.setStyleSheet("background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"font: 20pt \"华光超粗黑_CNKI\";")
        self.IdInput_2.setObjectName("IdInput_2")
        self.gridLayout_7.addWidget(self.IdInput_2, 0, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.tab4)
        self.comboBox.setMinimumSize(QtCore.QSize(250, 0))
        self.comboBox.setStyleSheet("background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"font: 20pt \"华光超粗黑_CNKI\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_7.addWidget(self.comboBox, 0, 2, 1, 1)
        self.searchbtn = QtWidgets.QPushButton(self.tab4)
        self.searchbtn.setStyleSheet("background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"font: 20pt \"华光超粗黑_CNKI\";")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("static/查找_find.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchbtn.setIcon(icon9)
        self.searchbtn.setIconSize(QtCore.QSize(30, 30))
        self.searchbtn.setObjectName("searchbtn")
        self.gridLayout_7.addWidget(self.searchbtn, 0, 4, 1, 1)
        self.tabelFrame = QtWidgets.QFrame(self.tab4)
        self.tabelFrame.setStyleSheet("background:#444444;")
        self.tabelFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tabelFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tabelFrame.setObjectName("tabelFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabelFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.gridLayout_7.addWidget(self.tabelFrame, 1, 0, 1, 5)
        self.tabWidget.addTab(self.tab4, icon9, "")
        self.tab5 = QtWidgets.QWidget()
        self.tab5.setObjectName("tab5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label = QtWidgets.QLabel(self.tab5)
        self.label.setStyleSheet("background:#444444;\n"
"font:120pt \"华光美黑_CNKI\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("static/更多2_more-two.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab5, icon10, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1165, 26))
        self.menubar.setObjectName("menubar")
        self.navigation = QtWidgets.QMenu(self.menubar)
        self.navigation.setObjectName("navigation")
        self.help = QtWidgets.QMenu(self.menubar)
        self.help.setObjectName("help")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setTitle("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("static/全科_general-branch.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu.setIcon(icon11)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.actionhelp = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../../../../.designer/backup/static/帮助_help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionhelp.setIcon(icon12)
        self.actionhelp.setObjectName("actionhelp")
        self.actionBlood_Cell_Detection = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("../../../../.designer/backup/static/点滴_infusion.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBlood_Cell_Detection.setIcon(icon13)
        self.actionBlood_Cell_Detection.setObjectName("actionBlood_Cell_Detection")
        self.actionMari = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("../../../../.designer/backup/static/病菌_germs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMari.setIcon(icon14)
        self.actionMari.setObjectName("actionMari")
        self.actionMore = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("../../../../.designer/backup/static/更多2_more-two.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMore.setIcon(icon15)
        self.actionMore.setObjectName("actionMore")
        self.actionHome = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("../../../../.designer/backup/static/首页_home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHome.setIcon(icon16)
        self.actionHome.setObjectName("actionHome")
        self.actionDatabase = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("../../../../.designer/backup/static/数据库_data.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDatabase.setIcon(icon17)
        self.actionDatabase.setObjectName("actionDatabase")
        self.navigation.addAction(self.actionDatabase)
        self.help.addAction(self.actionhelp)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.navigation.menuAction())
        self.menubar.addAction(self.help.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.timeLabel.setText(_translate("MainWindow", "timeLabel"))
        self.originImgLabel.setText(_translate("MainWindow", "原始图像"))
        self.resultImgLabel.setText(_translate("MainWindow", "结果图像"))
        self.resultTable.setSortingEnabled(False)
        item = self.resultTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "检测结果统计"))
        item = self.resultTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "红细胞计数"))
        item = self.resultTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "白细胞计数"))
        item = self.resultTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "血小板计数"))
        __sortingEnabled = self.resultTable.isSortingEnabled()
        self.resultTable.setSortingEnabled(False)
        self.resultTable.setSortingEnabled(__sortingEnabled)
        self.detectbtn.setText(_translate("MainWindow", "图像检测"))
        self.label_5.setText(_translate("MainWindow", "ID"))
        self.label_2.setText(_translate("MainWindow", "姓名"))
        self.label_3.setText(_translate("MainWindow", "性别"))
        self.label_4.setText(_translate("MainWindow", "年龄"))
        self.savebtn.setText(_translate("MainWindow", "保存图像"))
        self.uploadbtn.setText(_translate("MainWindow", "上传图像"))
        self.enterbtn.setText(_translate("MainWindow", "录入信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "血细胞检测"))
        self.uploadbtn2.setText(_translate("MainWindow", "上传图像"))
        self.groupBox.setTitle(_translate("MainWindow", "输出信息"))
        self.savebtn2.setText(_translate("MainWindow", "保存图像"))
        self.originImgLabel_2.setText(_translate("MainWindow", "原始图像"))
        self.resultImgLabel_2.setText(_translate("MainWindow", "结果图像"))
        self.detectbtn2.setText(_translate("MainWindow", "图像检测"))
        self.label_11.setText(_translate("MainWindow", "ID"))
        self.label_10.setText(_translate("MainWindow", "姓名"))
        self.label_13.setText(_translate("MainWindow", "性别"))
        self.label_12.setText(_translate("MainWindow", "年龄"))
        self.enterbtn2.setText(_translate("MainWindow", "录入信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "疟疾细胞检测"))
        self.batchbtn.setText(_translate("MainWindow", "上传文件夹"))
        self.generatebtn.setText(_translate("MainWindow", "生成图表"))
        self.progressbtn.setText(_translate("MainWindow", "处理任务"))
        self.savebtn3.setText(_translate("MainWindow", "保存结果"))
        self.label_6.setText(_translate("MainWindow", "结果图"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("MainWindow", "细胞核检测"))
        self.label_15.setText(_translate("MainWindow", "ID"))
        self.comboBox.setItemText(0, _translate("MainWindow", "血细胞检测"))
        self.comboBox.setItemText(1, _translate("MainWindow", "疟疾细胞检测"))
        self.searchbtn.setText(_translate("MainWindow", "点击查询"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab4), _translate("MainWindow", "数据查询"))
        self.label.setText(_translate("MainWindow", "敬请期待"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab5), _translate("MainWindow", "待开发"))
        self.navigation.setTitle(_translate("MainWindow", "导航"))
        self.help.setTitle(_translate("MainWindow", "帮助"))
        self.actionhelp.setText(_translate("MainWindow", "help"))
        self.actionBlood_Cell_Detection.setText(_translate("MainWindow", "Blood Cell Detection"))
        self.actionMari.setText(_translate("MainWindow", "Malaria Cell Detection"))
        self.actionMore.setText(_translate("MainWindow", "More"))
        self.actionHome.setText(_translate("MainWindow", "Home"))
        self.actionDatabase.setText(_translate("MainWindow", "Database"))
